### ISSUE TITLE
Build a wav file with multiple frequencies

### ISSUE THREAD

**Issue by jijoamt** [lowbyteproductions/Making-WAVs#2]
We would like to build a wav file with multiple frequencies for a specified duration for each frequency.

I'll try to explain the use case
1. Say we need to build a wav file with frequency ranging from 150MHz to 200MHz for the first 5 secs( the whole wave file from frequency 150MHz, 150.1MHz, 150.2MHz, etc up to 200MHz should end in 5 secs time) 
2. The next 10 secs should be from 200MHz to 300MHz
3. The next 15 secs should be from 300MHz to 400MHz

Once all the 3 wav files are generated, we need to combine/concat all these 3 into a single wav file of 30 secs (5+10+15)

Can you please let us know how can we achieve this using this code base?

**Comment by francisrstokes** [comment]
I presume this is related to issue #1? In any case, as I mentioned there, you need to select a sample rate that's appropriate for your signal. In this case, 800MHz to 1GHz would probably be a good choice. Then you need to follow the math laid out in the example in order to generate the desired frequencies (you can also refer to the original video to see a deeper explanation of that).

Concatenating wave files is quite straightforward, provided they have the same sample rate:

- Parse the files using the code in the repo.
- Read how much data is in each file, and allocate a buffer large enough to hold all 3
- Create a new file structure with the combined file size, and well literally concat the buffers together
- Write the file out

Small caveat though, is that the file you're talking about generating will be very big. Something like 56GiB assuming a sample rate of 1GHz. So the code as it is in this repo is not really the right kind of tool for this job. You could adapt the code to generate the file in a streaming manner - where you don't create a whole buffer at once, but rather compute the values and write them out to the file system in real time. That will take some more work, but is certainly possible.

Good luck, and let me know if it works out :+1:
